{
 "title": "Bungeecord single",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "servers", "query": { "query": "bungee_jvm_memory" } }
  ]
 },
 "panels": [
  {
   "title": "Total Online Players",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bungee_players_online_total{server_name=~\"$servers\"}",
     "legendFormat": "{{server}}"
    },
    {
     "expr": "sum(bungee_players_online_total{server_name=~\"$servers\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Total Events",
   "type": "graph",
   "gridPos": { "h": 12, "w": 7, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bungee_player_handshake_total{server_name=~\"$servers\"}[1m])",
     "legendFormat": "player handshakes"
    },
    {
     "expr": "increase(bungee_ping_total{server_name=~\"$servers\"}[1m])",
     "legendFormat": "server list pings"
    },
    {
     "expr": "increase(bungee_pre_login_total{server_name=~\"$servers\"}[1m])",
     "legendFormat": "player pre logins"
    },
    {
     "expr": "increase(bungee_post_login_total{server_name=~\"$servers\"}[1m])",
     "legendFormat": "player post logins"
    },
    {
     "expr": "increase(bungee_player_disconnects_total{server_name=~\"$servers\"}[1m])",
     "legendFormat": "player disconnects"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bungee_jvm_threads_current{server_name=~\"$servers\"}",
     "legendFormat": "TOTAL"
    },
    {
     "expr": "bungee_jvm_threads_state{server_name=~\"$servers\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bungee_jvm_memory{type='allocated', server_name=~\"$servers\"} - scalar(bungee_jvm_memory{type='free', server_name=~\"$servers\"})"
    }
   ]
  },
  {
   "title": "Online Servers",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bungee_servers_online_total{server_name=~\"$servers\"}"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "bungee_jvm_memory{type='allocated', server_name=~\"$servers\"} - scalar(bungee_jvm_memory{type='free', server_name=~\"$servers\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "bungee_jvm_memory{type='allocated', server_name=~\"$servers\"}",
     "legendFormat": "Allocated"
    }
   ]
  }
 ]
}