{
 "title": "Bungeecord",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "proxy", "query": { "query": "bungee_online_servers" } }
  ]
 },
 "panels": [
  {
   "title": "Online Players",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (bungee_online_players{proxy_name=~\"$proxy\"})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Events",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(bungee_pings_total{proxy_name=~\"$proxy\"}[1m]))",
     "legendFormat": "server list pings"
    },
    {
     "expr": "sum(increase(bungee_player_connects_total{proxy_name=~\"$proxy\"}[1m]))",
     "legendFormat": "connects"
    },
    {
     "expr": "sum(increase(bungee_pre_logins_total{proxy_name=~\"$proxy\"}[1m]))",
     "legendFormat": "pre logins"
    },
    {
     "expr": "sum(increase(bungee_post_logins_total{proxy_name=~\"$proxy\"}[1m]))",
     "legendFormat": "post logins"
    },
    {
     "expr": "sum(increase(bungee_player_disconnects_total{proxy_name=~\"$proxy\"}[1m]))",
     "legendFormat": "disconnects"
    }
   ]
  },
  {
   "title": "Player Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bungee_online_players{proxy_name=~\"$proxy\"})"
    }
   ]
  },
  {
   "title": "Hourly Stats",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(bungee_pings_total{proxy_name=~\"$proxy\"}[1h]))",
     "legendFormat": "list pings"
    },
    {
     "expr": "sum(increase(bungee_pre_logins_total{proxy_name=~\"$proxy\"}[1h]))",
     "legendFormat": "pre logins"
    },
    {
     "expr": "sum(increase(bungee_post_logins_total{proxy_name=~\"$proxy\"}[1h]))",
     "legendFormat": "post logins"
    },
    {
     "expr": "sum(increase(bungee_player_connects_total{proxy_name=~\"$proxy\"}[1h]))",
     "legendFormat": "connects"
    },
    {
     "expr": "sum(increase(bungee_player_disconnects_total{proxy_name=~\"$proxy\"}[1h]))",
     "legendFormat": "disconnects"
    }
   ]
  },
  {
   "title": "Daily Stats",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(bungee_pings_total{proxy_name=~\"$proxy\"}[1d]))",
     "legendFormat": "list pings"
    },
    {
     "expr": "sum(increase(bungee_pre_logins_total{proxy_name=~\"$proxy\"}[1d]))",
     "legendFormat": "pre logins"
    },
    {
     "expr": "sum(increase(bungee_post_logins_total{proxy_name=~\"$proxy\"}[1d]))",
     "legendFormat": "post logins"
    },
    {
     "expr": "sum(increase(bungee_player_connects_total{proxy_name=~\"$proxy\"}[1d]))",
     "legendFormat": "connects"
    },
    {
     "expr": "sum(increase(bungee_player_disconnects_total{proxy_name=~\"$proxy\"}[1d]))",
     "legendFormat": "disconnects"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bungee_jvm_threads_current{proxy_name=~\"$proxy\"})",
     "legendFormat": "{{server_name}} TOTAL"
    },
    {
     "expr": "sum by (state) (bungee_jvm_threads_state{proxy_name=~\"$proxy\"})",
     "legendFormat": "{{server_name}} {{state}}"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (type) (bungee_jvm_memory{type='free',proxy_name=~\"$proxy\"})",
     "legendFormat": "{{server_name}} free"
    }
   ]
  },
  {
   "title": "Online Proxies",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(bungee_jvm_memory{proxy_name=~\".*\"}) by (proxy_name))"
    }
   ]
  },
  {
   "title": "Servers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bungee_online_servers{proxy_name=~\"$proxy\"}",
     "legendFormat": "{{proxy_name}}"
    }
   ]
  },
  {
   "title": "$proxy RAM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 16 },
   "repeat": "proxies",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(bungee_jvm_memory{type='allocated', proxy_name=~\"$proxy\"}) - scalar(sum(bungee_jvm_memory{type='free', proxy_name=~\"$proxy\"}))"
    }
   ]
  }
 ]
}