{
 "title": "RedisBungee",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "proxies", "query": { "query": "bungee_jvm_memory" } },
   { "name": "main", "query": { "query": "bungee_servers_online_total" } }
  ]
 },
 "panels": [
  {
   "title": "Total Online Players",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (bungee_players_online_total)",
     "legendFormat": "{{server}}"
    },
    {
     "expr": "sum(bungee_players_online_total)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Total Events",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(bungee_ping_total[1m]))",
     "legendFormat": "server list pings"
    },
    {
     "expr": "sum(increase(bungee_client_connect_total[1m]))",
     "legendFormat": "client connects"
    },
    {
     "expr": "sum(increase(bungee_pre_login_total[1m]))",
     "legendFormat": "player pre logins"
    },
    {
     "expr": "sum(increase(bungee_post_login_total[1m]))",
     "legendFormat": "player post logins"
    },
    {
     "expr": "sum(increase(bungee_player_disconnects_total[1m]))",
     "legendFormat": "player disconnects"
    }
   ]
  },
  {
   "title": "Players",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bungee_players_online_total)"
    }
   ]
  },
  {
   "title": "Servers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bungee_servers_online_total{server_name=~\"$main\"}"
    }
   ]
  },
  {
   "title": "Proxies",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bungee_redis_bungee_proxies_online_total{server_name=~\"$main\"}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bungee_jvm_threads_current", "legendFormat": "{{server_name}} TOTAL" },
    { "expr": "bungee_jvm_threads_state", "legendFormat": "{{server_name}} {{state}}" }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 11, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "bungee_jvm_memory{type='free'}", "legendFormat": "{{server_name}} free" }
   ]
  },
  {
   "title": "$proxies JVM Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 10 },
   "repeat": "proxies",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bungee_jvm_memory{type='allocated', server_name=~\"$proxies\"} - scalar(bungee_jvm_memory{type='free', server_name=~\"$proxies\"})"
    }
   ]
  },
  {
   "title": "$proxies JVM Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bungee_jvm_memory{type='allocated', server_name=~\"$proxies\"} - scalar(bungee_jvm_memory{type='free', server_name=~\"$proxies\"})"
    }
   ]
  }
 ]
}