name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up JDK
        uses: actions/setup-java@master
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@master
        with:
          name: jar artifact
          path: /home/runner/work/bungeecord-prometheus-exporter/bungeecord-prometheus-exporter/target/bungeecord-prometheus-exporter-*.jar
